version: '3.8'

services:
  nobugs_bot:
    build: .
    container_name: nobugs_telegram_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./db:/usr/src/app/db # Пробрасываем папку с БД для сохранения данных
    command: python app/main.py

# --- Заготовка для перехода на PostgreSQL в продакшене ---
#  db:
#    image: postgres:13
#    container_name: nobugs_postgres
#    restart: always
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DB: ${POSTGRES_DB}
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#    ports:
#      - "5432:5432"

volumes:
  db_data:
#  postgres_data:

