# Ключевые слова для быстрой проверки, сгруппированные по интентам.
# Интент: Проверка статуса записи 
check_booking:
  - проверить запись
  - посмотреть мои занятия
  - на какое время я записан
  - какие у меня уроки
  - напомни про запись

# Интент: Отмена записи
cancellation:
  - отменить 
  - отменить занятие
  - отмени 
  - я хочу отказаться
  - отмена 
  - отказ
  - не придём
  - не сможем прийти
  - не сможем придти
  - гас не будет
# Интент: Перенос записи 
reschedule:
  - перенести 
  - перенести занятие
  - перезаписаться на другое время
  - поменять время урока
  - изменить запись
  - перенос
  - поменять 

# Интент: Запись на пробный урок 
booking_request:
- записаться на урок
- хочу на пробное
- запиши на пробное
- записать ребенка
- забронировать время
- есть свободные слоты
- как записаться
- хочу записаться
- записаться
- на пробник


# Интент: Запрос цены
price_request:
  - сколько стоит
  - какая цена
  - стоимость
  - цены
  - прайс

# Интент: Уточнение про льготы 
social_status_info:
  - я многодетная мама
  - я многодетный отец
  - у меня много детей
  - мы многодетные
  - для многодетных
  - одинокий родитель
  - мать-одиночка
  - отец-одиночка
  - какая у вас скидка

# Интент: Приветствие (если захотите обрабатывать его отдельно)
greeting:
  - привет
  - добрый день
  - здравствуйте

# Интент: Просьба позвать человека
human_operator:
  - позвать оператора
  - поговорить с человеком
  - нужен менеджер
