# Ключевые слова для быстрой проверки, сгруппированные по интентам.

# Интент: Отмена записи
cancellation:
  - отменить урок
  - отмена записи
  - отмени запись
  - не смогу прийти
  - отказаться от урока
  - перенести встречу

# Интент: Запрос цены
price_request:
  - сколько стоит
  - какая цена
  - стоимость
  - цены
  - прайс

# Интент: Приветствие (если захотите обрабатывать его отдельно)
greeting:
  - привет
  - добрый день
  - здравствуйте

# Интент: Просьба позвать человека
human_operator:
  - позвать оператора
  - поговорить с человеком
  - нужен менеджер
