# Ключевые слова для быстрой проверки, сгруппированные по интентам.
# Интент: Отмена записи
cancellation:
- отменить урок
- отмена записи
- отмени запись
- не смогу прийти
- отказаться от урока
- отменить пробное занятие
- отменить занятие 

# Интент: Перенос записи 
reschedule:
- перенести урок
- перенести встречу
- перенести запись
- изменить время
- другое время
- перенести занятие

# Интент: Запись на пробный урок 
booking_request:
- записаться на урок
- хочу на пробное
- запиши на пробное
- записать ребенка
- забронировать время
- есть свободные слоты
- как записаться
- хочу записаться



# Интент: Запрос цены
price_request:
  - сколько стоит
  - какая цена
  - стоимость
  - цены
  - прайс

# Интент: Приветствие (если захотите обрабатывать его отдельно)
greeting:
  - привет
  - добрый день
  - здравствуйте

# Интент: Просьба позвать человека
human_operator:
  - позвать оператора
  - поговорить с человеком
  - нужен менеджер
