# Ключевые слова для быстрой проверки, сгруппированные по интентам.

# Интент: Запись на пробный урок
booking_request:
  keywords:
    - "записаться на урок"
    - "хочу на пробное"
    - "запиши на пробное"
    - "записать ребенка"
    - "забронировать время"
    - "есть свободные слоты"
    - "как записаться"
    - "хочу записаться"
    - "записаться"
    - "на пробник"
    - "хочу попробовать"
    - "давайте начнем"

# Интент: Отмена записи
cancellation:
  keywords:
    - "отменить"
    - "отменить занятие"
    - "отмени"
    - "я хочу отказаться"
    - "отмена"
    - "отказ"
    - "не придём"
    - "не сможем прийти"
    - "не сможем придти"
    - "нас не будет"
    - "мы передумали"
    - "снимите бронь"

# Интент: Перенос записи
reschedule:
  keywords:
    - "перенести"
    - "перенести занятие"
    - "перезаписаться на другое время"
    - "поменять время урока"
    - "изменить запись"
    - "перенос"
    - "поменять"

# Интент: Проверка статуса записи
check_booking:
  keywords:
    - "проверить запись"
    - "посмотреть мои занятия"
    - "на какое время я записан"
    - "какие у меня уроки"
    - "напомни про запись"
    - "когда у нас урок"
    - "подтвердите запись"

# Интент: Запрос цены
price_request:
  keywords:
    - "сколько стоит"
    - "какая цена"
    - "стоимость"
    - "цены"
    - "прайс"
  callback_keys:
    - "price_request"

# Интент: Вопросы о содержании курса
course_details:
  keywords:
    - "что будут делать"
    - "что входит в курс"
    - "программа курса"
    - "какие темы изучают"
    - "расскажите о курсе"
  callback_keys:
    - "course_details"

# Интент: В чем разница между курсами
course_difference:
  keywords:
    - "в чем разница"
    - "отличия курсов"
    - "какой курс лучше"
  callback_keys:
    - "course_difference"

# Интент: Уточнение про льготы
social_status_info:
  keywords:
    - "я многодетная мама"
    - "я многодетный отец"
    - "у меня много детей"
    - "мы многодетные"
    - "для многодетных"
    - "одинокий родитель"
    - "мать-одиночка"
    - "отец-одиночка"
    - "какая у вас скидка"
    
# Интент: Вопрос об индивидуальности занятий
lesson_individuality:
  keywords:
    - "занятия индивидуальные"
    - "в группе или один на один"
    - "сколько человек в группе"
    - "занятия групповые"
    - "формат занятий"

# Интент: Приветствие
greeting:
  keywords:
    - "привет"
    - "добрый день"
    - "здравствуйте"

# Интент: Просьба позвать человека
human_operator:
  keywords:
    - "позвать оператора"
    - "поговорить с человеком"
    - "нужен менеджер"
